swagger: "2.0"
info:
  title: bookmeter
  description: bookmeterのパクリ
  version: "1.0"
host: 127.0.0.1:5000
basePath: /
schemes:
  - http
  - https
paths:
  /book/{isbn}:
    get:
      summary: "書籍情報を探す"
      parameters:
        - in: "path"
          name: "isbn"
          required: true
      consumes:
        - "text/plain"
      produces:
        - "application/json"
        - "text/plain"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Not Found"
  /status:
    post:
      summary: "読了状態を記録する"
      consumes:
        - "text/plain"
      produces:
        - "application/json"
      parameters:
        - in: "ISBN"
          name: "isbn"
          required: true
        - in: "status"
          name: "status"
          required: true
        - name: "token"
          in: "usertoken"
          required: true
      responses:
        "401":
          description: "Invalid token"
